### ISSUE TITLE
missing error catch in deep_get

### ISSUE THREAD

**Issue by tidalf** [tidalf/plugin.audio.qobuz#235]
```
10:51:21.512 T:24284   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\default.py", line 18, in <module>
                                                app.start()
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\application.py", line 41, in start
                                                self.bootstrap.dispatch()
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\bootstrap.py", line 148, in dispatch
                                                return r.run()
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\renderer\xbmc.py", line 190, in run
                                                _ret = populate_node(self.root, options)
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\renderer\xbmc.py", line 64, in populate_node
                                                return node.populating(options)
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode\main.py", line 386, in populating
                                                options.xdir.add_node(child)):
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\gui\directory.py", line 83, in add_node
                                                return self.__add_node(node)
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\gui\directory.py", line 86, in __add_node
                                                item = node.makeListItem(replaceItems=self.replaceItems)
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\user.py", line 82, in makeListItem
                                                item.setProperty('artist_description', self.get_description())
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\user.py", line 60, in get_description
                                                to='color'),
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode\main.py", line 177, in get_property
                                                value = get_property_helper(self.data, path, to)
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode\main.py", line 38, in get_property_helper
                                                _path, value = properties.deep_get(data, path)
                                              File "C:\Users\Cyril\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\util\properties.py", line 59, in deep_get
                                                if part not in root:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
```
```
workaround (dirty try catch in L58 of resources\lib\qobuz\util\properties.py): 
    for _i, part in enumerate(parts):
        try:
          root = root[part]
        except: 
		  root = ""
```

**Comment by showi** [comment]
should it not easier to do something like:

```
if not root or part not in root:
  return ''
```
