### ISSUE TITLE
Can't search artist/album/tracks nomore - see error log

### ISSUE THREAD

**Issue by thelucifermorningstar** [tidalf/plugin.audio.qobuz#246]
## Greetings
First of all, thank you for creating this rly handy Qobuz Kodi plugin!
I've no clue when this started, but I know it was working a few months ago...

## Issue description
Can't search artist/album/tracks nomore
Mind you, when entering the word 'love' in Album search, it does show results, so I think it has to do with pagination.

## Error log
`2019-10-01 23:29:52.385 T:1216   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.qobuz/?mode=1&nt=512&offset=0&search-type=albums
2019-10-01 23:29:52.390 T:12744   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.qobuz/?mode=1&nt=512&offset=0&search-type=albums) failed
2019-10-01 23:30:08.567 T:12744 WARNING: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2019-10-01 23:30:14.756 T:9308 WARNING: Previous line repeats 23 times.
2019-10-01 23:30:14.756 T:9308   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'limit'
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\default.py", line 35, in <module>
                                                boot.dispatch()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\bootstrap.py", line 160, in dispatch
                                                return r.run()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\renderer\xbmc.py", line 64, in run
                                                self.whiteFlag, self.blackFlag)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode.py", line 379, in populating
                                                self.__add_pagination(self.data)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode.py", line 191, in __add_pagination
                                                if items['limit'] is None:
                                            KeyError: 'limit'
                                            -->End of Python script error report<--
2019-10-01 23:30:14.801 T:15100   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.qobuz/?mode=1&nt=512&offset=0&search-type=tracks
2019-10-01 23:30:14.805 T:12744   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.qobuz/?mode=1&nt=512&offset=0&search-type=tracks) failed
2019-10-01 23:30:22.118 T:10316   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'limit'
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\default.py", line 35, in <module>
                                                boot.dispatch()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\bootstrap.py", line 160, in dispatch
                                                return r.run()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\renderer\xbmc.py", line 64, in run
                                                self.whiteFlag, self.blackFlag)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode.py", line 379, in populating
                                                self.__add_pagination(self.data)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode.py", line 191, in __add_pagination
                                                if items['limit'] is None:
                                            KeyError: 'limit'
                                            -->End of Python script error report<--
2019-10-01 23:30:22.150 T:17908   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.qobuz/?mode=1&nt=512&offset=0&search-type=artists
2019-10-01 23:30:22.157 T:12744   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.qobuz/?mode=1&nt=512&offset=0&search-type=artists) failed

2019-10-01 23:30:56.195 T:1900   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'limit'
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\default.py", line 35, in <module>
                                                boot.dispatch()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\bootstrap.py", line 160, in dispatch
                                                return r.run()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\renderer\xbmc.py", line 64, in run
                                                self.whiteFlag, self.blackFlag)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode.py", line 379, in populating
                                                self.__add_pagination(self.data)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.audio.qobuz\resources\lib\qobuz\node\inode.py", line 191, in __add_pagination
                                                if items['limit'] is None:
                                            KeyError: 'limit'
                                            -->End of Python script error report<--
2019-10-01 23:30:56.231 T:3020   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.qobuz/?mode=1&nt=512&offset=0&search-type=artists
2019-10-01 23:30:56.233 T:12036   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.qobuz/?mode=1&nt=512&offset=0&search-type=artists) failed`

**Comment by geofstro** [comment]
I had the same problem. I simply put a “try: … except: pass statement around those lines in the “inode.py” file and search now works perfectly.

Perhaps that change (or something better?) can be submitted for the next version?
